# Name of the blog
name: This is it
description: Doing something
author: juanmi

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 
baseurl: blog

url: http://https://juancabrerait.github.io

# How many articles do you wish to appear on the front page:
paginate: 3

theme: jekyll-theme-minimal


avatar: https://i.ytimg.com/vi/fsIvH8qVi7o/maxresdefault.jpg